/// The type of a node in the tup dependency graph.
///
/// These values must match the C enum exactly, as they are stored
/// in the SQLite database as integers.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(i32)]
pub enum NodeType {
    /// Source file (not generated by any command)
    File = 0,
    /// Command node (a build rule from a Tupfile)
    Cmd = 1,
    /// Directory
    Dir = 2,
    /// @-variable node
    Var = 3,
    /// Generated/output file (produced by a command)
    Generated = 4,
    /// Ghost node (placeholder for deleted/missing node still referenced)
    Ghost = 5,
    /// Output group (aggregates multiple outputs)
    Group = 6,
    /// Generated directory (created by build commands)
    GeneratedDir = 7,
    /// Virtual root node (parent of all top-level entries)
    Root = 8,
}

impl NodeType {
    /// Convert from an i32 database value.
    pub fn from_i32(value: i32) -> Option<Self> {
        match value {
            0 => Some(Self::File),
            1 => Some(Self::Cmd),
            2 => Some(Self::Dir),
            3 => Some(Self::Var),
            4 => Some(Self::Generated),
            5 => Some(Self::Ghost),
            6 => Some(Self::Group),
            7 => Some(Self::GeneratedDir),
            8 => Some(Self::Root),
            _ => None,
        }
    }

    /// Convert to an i32 for database storage.
    pub fn as_i32(self) -> i32 {
        self as i32
    }

    /// Get a human-readable string for this node type.
    ///
    /// Matches the output of `tup_db_type()` in the C implementation.
    pub fn as_str(self) -> &'static str {
        match self {
            Self::File => "normal file",
            Self::Cmd => "command",
            Self::Dir => "directory",
            Self::Var => "variable",
            Self::Generated => "generated file",
            Self::Ghost => "ghost",
            Self::Group => "group",
            Self::GeneratedDir => "generated dir",
            Self::Root => "root",
        }
    }

    /// Returns true if this is a file-like node (File or Generated).
    pub fn is_file(self) -> bool {
        matches!(self, Self::File | Self::Generated)
    }

    /// Returns true if this is a directory-like node (Dir or GeneratedDir).
    pub fn is_dir(self) -> bool {
        matches!(self, Self::Dir | Self::GeneratedDir)
    }
}

impl std::fmt::Display for NodeType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_node_type_values() {
        assert_eq!(NodeType::File.as_i32(), 0);
        assert_eq!(NodeType::Cmd.as_i32(), 1);
        assert_eq!(NodeType::Dir.as_i32(), 2);
        assert_eq!(NodeType::Var.as_i32(), 3);
        assert_eq!(NodeType::Generated.as_i32(), 4);
        assert_eq!(NodeType::Ghost.as_i32(), 5);
        assert_eq!(NodeType::Group.as_i32(), 6);
        assert_eq!(NodeType::GeneratedDir.as_i32(), 7);
        assert_eq!(NodeType::Root.as_i32(), 8);
    }

    #[test]
    fn test_node_type_roundtrip() {
        for i in 0..=8 {
            let nt = NodeType::from_i32(i).unwrap();
            assert_eq!(nt.as_i32(), i);
        }
    }

    #[test]
    fn test_node_type_invalid() {
        assert!(NodeType::from_i32(-1).is_none());
        assert!(NodeType::from_i32(9).is_none());
        assert!(NodeType::from_i32(100).is_none());
    }

    #[test]
    fn test_node_type_display() {
        assert_eq!(format!("{}", NodeType::File), "normal file");
        assert_eq!(format!("{}", NodeType::Cmd), "command");
        assert_eq!(format!("{}", NodeType::Ghost), "ghost");
    }

    #[test]
    fn test_is_file() {
        assert!(NodeType::File.is_file());
        assert!(NodeType::Generated.is_file());
        assert!(!NodeType::Dir.is_file());
        assert!(!NodeType::Cmd.is_file());
    }

    #[test]
    fn test_is_dir() {
        assert!(NodeType::Dir.is_dir());
        assert!(NodeType::GeneratedDir.is_dir());
        assert!(!NodeType::File.is_dir());
    }
}
